### ISSUE TITLE
Use `Wox.Infrastructure.StringMatcher.FuzzySearch` for string matching

### ISSUE THREAD

**Issue by 8LWXpg** [davidegiacometti/PowerToys-Run-EdgeFavorite#12]
Current implementation uses `String.StartsWith`, which is less convenient in searching.

**Comment by davidegiacometti** [comment]
Hi @8LWXpg

This is by design:
- When the **Search as tree** option is enabled the favorite hierarchy is treated as a tree and the match is done using "starts with". This is similar to what the Folder plugin does.
- When the **Search as tree** option is disabled all the favorites are queries in a flat way and the match is done using "fuzzy search".

**Comment by 8LWXpg** [comment]
Thanks for the explanation.
