### ISSUE TITLE
Feature Request: Option to open in a new window

### ISSUE THREAD

**Issue by mlhdeveloper** [davidegiacometti/PowerToys-Run-EdgeFavorite#9]
A setting to always open any Favorite in a new window and/or a way to specify when you want to open a Favorite in a new window would be very convenient.

**Comment by davidegiacometti** [comment]
Hi @mlhdeveloper

Thanks for the suggestion: it's achievable passing the `--new-window` arg when Edge is opened.
I would like to get more info in order to understand if this is more suitable for a setting option or for a result action (like copy URL and open in private):

- Does Edge allow to change the default behavior? (can't find the option 🤔)
- What's the use case for opening a new window instead of a new tab?

**Comment by mlhdeveloper** [comment]
> * What's the use case for opening a new window instead of a new tab?

Sorry for the delayed response, @davidegiacometti! My general use case is I will usually switch to a new window if I'm temporarily switching to a different task/topic, so if switching to that task requires opening a Favorite, it would be more efficient if I could have it open in a new window rather than having to drag it out of an existing window.

**Comment by davidegiacometti** [comment]
Thanks for the feedback.
So the request is for a new action like "Copy URL" and "Open in InPrivate" rather than an options in the plugin settings.

**Comment by mlhdeveloper** [comment]
Yes, exactly. So there'd be 3 options listed when opening a Favorite via PowerToys Run, like:
`Copy URL` `Open new window` `Open InPrivate`

**Comment by davidegiacometti** [comment]
I have just released version [0.5.1](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.5.1) that includes this suggestion.
